#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file contains the user-editable part of the client configuration.
# © 2012 Mezgrman.

class commands:
	cmd_prefix = u"/"
	tweet = cmd_prefix + u"tweet"
	retweet = cmd_prefix + u"rt"
	favorite = cmd_prefix + u"fav"
	unfavorite = cmd_prefix + u"unfav"
	follow = cmd_prefix + u"follow"
	unfollow = cmd_prefix + u"unfollow"
	last_tweets = cmd_prefix + u"last"
	profile = cmd_prefix + u"profile"
	reply = cmd_prefix + u"reply"
	mentions = cmd_prefix + u"me"
	conversation = cmd_prefix + u"conv"
	relationship = cmd_prefix + u"rel"
	delete = cmd_prefix + u"del"
	replyall = cmd_prefix + u"rall"
	dump = cmd_prefix + u"dump"
	trends = cmd_prefix + u"trends"
	logout = cmd_prefix + u"logout"
	clear = cmd_prefix + u"clear"
	filter_word = cmd_prefix + u"filterword"
	filter_user = cmd_prefix + u"filteruser"
	filter_client = cmd_prefix + u"filterclient"
	filter_regex = cmd_prefix + u"filterregex"
	unfilter_word = cmd_prefix + u"unfilterword"
	unfilter_user = cmd_prefix + u"unfilteruser"
	unfilter_client = cmd_prefix + u"unfilterclient"
	unfilter_regex = cmd_prefix + u"unfilterregex"
	list_word_filter = cmd_prefix + u"wordfilter"
	list_user_filter = cmd_prefix + u"userfilter"
	list_client_filter = cmd_prefix + u"clientfilter"
	list_regex_filter = cmd_prefix + u"regexfilter"
	messages = cmd_prefix + u"dms"
	message = cmd_prefix + u"dm"
	block = cmd_prefix + u"block"
	unblock = cmd_prefix + u"unblock"
	report_as_spam = cmd_prefix + u"report"
	help = cmd_prefix + u"help"
	afk_mode_on = cmd_prefix + u"afkon"
	afk_mode_off = cmd_prefix + u"afkoff"
	lists = cmd_prefix + u"lists"
	create_list = cmd_prefix + u"createlist"
	highlight_word = cmd_prefix + u"highlightword"
	highlight_user = cmd_prefix + u"highlightuser"
	highlight_client = cmd_prefix + u"highlightclient"
	highlight_regex = cmd_prefix + u"highlightregex"
	unhighlight_word = cmd_prefix + u"unhighlightword"
	unhighlight_user = cmd_prefix + u"unhighlightuser"
	unhighlight_client = cmd_prefix + u"unhighlightclient"
	unhighlight_regex = cmd_prefix + u"unhighlightregex"
	list_highlighted_words = cmd_prefix + u"highlightedwords"
	list_highlighted_users = cmd_prefix + u"highlightedusers"
	list_highlighted_clients = cmd_prefix + u"highlightedclients"
	list_highlighted_regexes = cmd_prefix + u"highlightedregexes"
	refresh = cmd_prefix + u"refresh"

class var:
	notify_freq = 750
	notify_dur = 25
	statusbar_time_format = "%d.%m.%Y %H:%M:%S"
	tweet_command_required = False
	last_tweet_count = 10
	mentions_count = 25
	messages_count = 10
	tweet_preview_length = 50
	default_notification_timeout = 1.0
	palette = [
		('statusbar', 'light gray', 'default'),
		('statusbar bold', 'light gray, bold', 'default', 'bold'),
		('feed', 'light gray', 'default'),
		('feed bold', 'light gray, bold', 'default', 'bold'),
		('cmdline', 'light gray', 'default'),
		('cmdline bold', 'light gray, bold', 'default', 'bold'),
		('dialog', 'white', 'dark cyan'),
		('dialog bold', 'white, bold', 'dark cyan', 'bold'),
		('button', 'white', 'dark blue'),
		('button bold', 'white, bold', 'dark blue', 'bold'),
		('button focus', 'white', 'dark red'),
		('button focus bold', 'white, bold', 'dark red', 'bold'),
		('edit', 'white', 'dark red'),
		('edit bold', 'white, bold', 'dark red', 'bold'),
		('list', 'white', 'dark blue'),
		('list bold', 'white, bold', 'dark blue', 'bold'),
		('list selected', 'white', 'dark red'),
		('list selected bold', 'white, bold', 'dark red', 'bold'),
		('short code', 'light blue', 'default'),
		('author', 'light gray, bold', 'default', 'bold'),
		('tweet', 'light gray', 'default'),
		('mention', 'light cyan, bold', 'default', 'bold'),
		('notification', 'light green', 'default'),
		('favorite', 'yellow', 'default'),
		('favorite mention', 'yellow, bold', 'default', 'bold'),
		('highlighted', 'light green', 'default'),
		('warning', 'yellow', 'default'),
		('error', 'light red', 'default'),
	]

class strings:
	window_title_no_notifications = u"@%(username)s - %(name)s v%(version)s"
	window_title_notifications = u"(%(notifications)i) @%(username)s - %(name)s v%(version)s"
	verifier_prompt = u"Please enter the verifier code you got from Twitter: "
	favorite_notification = u"%s (@%s) favorited your tweet '%s'."
	unfavorite_notification = u"%s (@%s) unfavorited your tweet '%s'."
	follower_notification = u"%s (@%s) followed you."
	statusbar_left = u"@%(username)s | %(followers)i Followers | Following %(following)i | %(tweets)i Tweets | %(favorites)i Favorites"
	statusbar_right = u"%(cached_tweets)i tweets cached | %(time)s | %(countdown)s"
	countdown_updating = u"Updating..."
	countdown = u"Next update in %i:%02i"
	prompt = u"[%03.f] > "
	prompt_loading = u"[loading] > "
	favorited = u"Favorited \"%s\" by @%s."
	unfavorited = u"Unfavorited \"%s\" by @%s."
	followed = u"Followed @%s."
	unfollowed = u"Unfollowed @%s."
	last_tweets_header = u"Last %s tweets by @%s\nHit Enter to reply to the selected tweet."
	profile_header = u"%s (@%s)"
	profile_item_name = u"Name: %s"
	profile_item_location = u"Location: %s"
	profile_item_website = u"Website: %s"
	profile_item_bio = u"%s"
	profile_item_followers = u"Followers: %s"
	profile_item_following = u"Following: %s"
	profile_item_tweets = u"Tweets: %s"
	profile_item_listed = u"Listed: %sx"
	profile_item_lang = u"Language: %s"
	profile_item_timezone = u"Time zone: %s"
	mentions_header = u"Last %s mentions\nHit Enter to reply to the selected tweet."
	messages_header = u"Last %s direct messages\nHit Enter to reply to the selected message."
	conversation_header = u"Conversation\nHit Enter to reply to all users included in the selected tweet."
	rel_both = u"%s <=> %s"
	rel_i_follow = u"%s => %s"
	rel_following_me = u"%s <= %s"
	rel_none = u"%s - %s"
	dump_header = u"Tweet Dump\n"
	dump_short_code = u"Internal short code: %s"
	dump_internal_id = u"Internal Tweet ID: %s"
	dump_internal_in_reply_to = u"Internal in reply to status ID: %s"
	dump_internal_username = u"Internal username: %s"
	dump_internal_text = u"Internal text: %s"
	dump_id = u"ID: %s"
	dump_in_reply_to = u"In reply to status ID: %s"
	dump_author = u"Author: %s"
	dump_text = u"Text: %s"
	dump_source = u"Source: %s"
	trends_header = u"Current Global Trends\nHit Enter to write a tweet about the selected trend."
	delete_notification = u"%s deleted their tweet '%s' (%s)."
	filtered_word = u"Now filtering out \"%s\"."
	filtered_user = u"Now filtering out user @%s."
	filtered_client = u"Now filtering out client \"%s\"."
	filtered_regex = u"Now filtering out regular expression \"%s\"."
	unfiltered_word = u"No longer filtering out \"%s\"."
	unfiltered_user = u"No longer filtering out user @%s."
	unfiltered_client = u"No longer filtering out client \"%s\"."
	unfiltered_regex = u"No longer filtering out regular expression \"%s\"."
	word_filter = u"Words currently in word filter:\n\n%s"
	user_filter = u"Users currently in user filter:\n\n%s"
	client_filter = u"Clients currently in client filter:\n\n%s"
	regex_filter = u"Regular expressions currently in regex filter:\n\n%s"
	highlighted_word = u"Now highlighting \"%s\"."
	highlighted_user = u"Now highlighting user @%s."
	highlighted_client = u"Now highlighting client \"%s\"."
	highlighted_regex = u"Now highlighting regular expressions \"%s\"."
	unhighlighted_word = u"No longer highlighting \"%s\"."
	unhighlighted_user = u"No longer highlighting user @%s."
	unhighlighted_client = u"No longer highlighting client \"%s\"."
	unhighlighted_regex = u"No longer highlighting regular expression \"%s\"."
	highlighted_words = u"Words currently highlighted:\n\n%s"
	highlighted_users = u"Users currently highlighted:\n\n%s"
	highlighted_clients = u"Clients currently highlighted:\n\n%s"
	highlighted_regexes = u"Regular expressions currently highlighted:\n\n%s"
	message_sent = u"Your direct message has been sent to @%s."
	blocked = u"@%s has been blocked."
	unblocked = u"@%s has been unblocked."
	reported_as_spam = u"@%s has been blocked and reported as spam."
	help_header = u"Help"
	quit_confirmation = u"Really quit?"
	mention_select_action = u"What would you like to do?"
	reply = u"Reply"
	view_conversation = u"View conversation"
	use_twitlonger = u"Tweet is longer than 140 characters.\n\nPost it to TwitLonger? (No additional effort for you!)"
	use_twextender = u"Tweet is longer than 140 characters.\n\nPost it to TwExtender? (No additional effort for you!)"
	twitlonger_protected_account = u"Your account is protected.\nIf you use TwitLonger, everybody who has the link can see this tweet.\n\nContinue anyway?"
	twextender_protected_account = u"Your account is protected.\nIf you use TwExtender, everybody who has the link can see this tweet.\n\nContinue anyway?"
	afk_mode_enabled = u"AFK mode enabled. Showing only mentions, direct messages, favorite and follower notifications."
	afk_mode_disabled = u"AFK mode disabled. Showing all new tweets."
	deleted = u"Your tweet \"%s\" has been deleted."
	message_deleted = u"Your direct message \"%s\" to @%s has been deleted."
	lists_header = u"Your lists\nHit Enter to view the details of the selected list."
	list_details_header = u"%s"
	list_details_item_description = u"%s"
	list_details_item_privacy = u"Privacy: %s"
	list_details_item_members = u"Members: %s"
	list_details_item_subscribers = u"Subscribers: %s"
	button_members = u"View members"
	button_edit = u"Edit"
	update_available = u"An update for %s is available!\n\nLatest version: %s\n\nChanges include:\n%s\n\nGo to http://dev.mezgrman.de/flutterfeed to download it."
	button_yes = u"Yes"
	button_no = u"No"
	button_ok = u"OK"
	list_members_header = u"Members of \"%s\"\nHit Enter to remove the selected user from the list."
	list_members_item = u"%s (@%s)"
	edit_profile_header = u"Edit your profile"
	caption_name = u"Name:"
	caption_location = u"Location:"
	caption_website = u"Website:"
	caption_bio = u"Bio:"
	profile_updated = u"Your profile has been updated."
	button_edit_profile = u"Edit profile"
	reconnected_after_stream_error = u"Successfully reconnected after a stream error."
	edit_list_header = u"Edit your list \"%s\""
	caption_privacy = u"Privacy (public or private):"
	caption_description = u"Description:"
	list_updated = u"Your list \"%s\" has been updated."
	remove_user_from_list = u"Remove @%s from your list \"%s\"?"
	list_member_removed = u"@%s has been removed from your list \"%s\"."
	button_add_member = u"Add member"
	button_delete_list = u"Delete list"
	add_list_member = u"Add a member to your list \"%s\""
	list_member_added = u"@%s has been added to your list \"%s\"."
	delete_list = u"Do you really want to delete your list \"%s\"?"
	list_deleted = u"Your list \"%s\" has been deleted."
	create_list_header = u"Create a new list"
	list_created = u"Your list \"%s\" has been created."
	caption_username = u"Username:"
	message_popup_notification = u"New direct message from @%s"
	notification_title = u"%s (@%s)"
	args_nobackfill = u"Turn off timeline backfilling on startup"
	args_manual = u"Run in \"manual\" mode (no automatic timeline refreshing)"
	args_tweet = u"Send a tweet with the given text and exit"
	args_keywords = u"Comma separated list of keywords to start a stream for instead of starting the user's timeline stream"
	args_users = u"Comma separated list of user IDs to start a stream for instead of starting the user's timeline stream"
	args_locations = u"Comma separated list of location bounding box coordinates to start a stream for instead of starting the user's timeline stream"
	args_database = u"The database file to use"
	args_account = u"The account / profile to use. If not specified, use the default account. If no account with the given name is found, it is created."

class error:	
	timeout = u"Timeout. Reconnecting in %i seconds..."
	stream_error = u"Stream error. Reconnecting in %i seconds..."
	stream_reconnecting = u"Reconnecting..."
	api_error = u"API Error: %s"
	generic_error = u"Generic Error."
	data_required = u"Not enough arguments for command '%s'."
	invalid_short_code = u"Invalid short code '%s' in command '%s %s'."
	invalid_command = u"%s: Invalid command."
	filter_word_error = u"\"%s\" is already in the word filter."
	filter_user_error = u"@%s is already in the user filter."
	filter_client_error = u"\"%s\" is already in the client filter."
	filter_regex_error = u"\"%s\" is already in the regular expression filter."
	unfilter_word_error = u"\"%s\" is not in the word filter."
	unfilter_user_error = u"@%s is not in the user filter."
	unfilter_client_error = u"\"%s\" is not in the client filter."
	unfilter_regex_error = u"\"%s\" is not in the regular expression filter."
	highlight_word_error = u"\"%s\" is already highlighted."
	highlight_user_error = u"@%s is already highlighted."
	highlight_client_error = u"\"%s\" is already highlighted."
	highlight_regex_error = u"Regular expression \"%s\" is already highlighted."
	unhighlight_word_error = u"\"%s\" is not highlighted."
	unhighlight_user_error = u"@%s is not highlighted."
	unhighlight_client_error = u"\"%s\" is not highlighted."
	unhighlight_regex_error = u"Regular expression \"%s\" is not highlighted."
	twitlonger_error = u"Error posting the tweet to TwitLonger: %s"
	twextender_error = u"Error posting the tweet to TwExtender: %s"
	afk_mode_already_enabled = u"AFK mode is already enabled."
	afk_mode_not_enabled = u"AFK mode is not enabled."
	retweet_failed = u"You cannot retweet this tweet.\n\nIt might be from a protected user or you might have already retweeted it."
	feature_not_yet_implemented = u"This feature has not yet been implemented."
